name: CI

on:
  push:
    branches:
      - main
      - develop
      - hotfix
      - "features/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  installation:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install manager tool & npm package
        run: |
          npm i -g lerna
          npm run bootstrap -- --no-ci

      - name: Log context
        env:
          CTX: ${{ toJSON(github) }}
        run: echo "$CTX"

      - name: Release package
        if: github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
        env:
          CTX: ${{ toJSON(github) }}
        run: echo "$CTX"
