name: CI

on:
  push:
    branches:
      - main
      - develop
      - hotfix
      - "features/**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  deployment:
    runs-on: ubuntu-latest

    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      fail-fast: false

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install manager tool & npm package
        run: |
          npm i -g lerna
          npm run bootstrap -- --no-ci

      - name: Release package@next
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          npm run publish -- --positional=patch --dist-tag=next --no-git-reset --yes

      - name: Release package@latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          npm run publish -- --positional=major --dist-tag=latest --no-git-reset --yes

